In [ ]:
#importing
import numpy as np

In [ ]:
a=np.ones((8,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#random module is subpackage of numpy
A = np.random.rand(1)
print(A)

[0.89825888]


In [ ]:
A = np.random.rand(8,4)#rand-range is between 0 and 1
print(A)

[[0.32873029 0.78920728 0.3120945  0.12859557]
 [0.71434134 0.859078   0.92554531 0.5745351 ]
 [0.67438754 0.62755434 0.61574726 0.54858465]
 [0.91584306 0.96437234 0.84370795 0.23251861]
 [0.44752889 0.2324742  0.79701939 0.09078394]
 [0.58843501 0.9630972  0.20750246 0.99240076]
 [0.73154262 0.20606377 0.10885476 0.55965161]
 [0.50215488 0.63436634 0.12719595 0.45184315]]


In [ ]:
A = 10*np.random.rand(8,4)#rand-range is between 0 and 1
print(A)

[[2.26933008 5.01704336 1.27445253 3.28173551]
 [5.46233851 0.61851618 0.88115588 1.51075367]
 [6.35212125 3.8241801  4.02337161 8.96063566]
 [8.81382142 0.39372357 6.10492359 6.0274501 ]
 [6.47781327 5.00207943 7.06690424 9.34968645]
 [3.65656758 2.99228649 1.14963033 9.30449769]
 [3.83989899 0.86981268 5.33968307 8.17908825]
 [0.11659199 9.53617125 9.32579118 7.99721156]]


In [ ]:
A = np.floor(10*np.random.rand(8,4))#rand-range is between 0 and 1
print(A)

[[2. 5. 3. 1.]
 [5. 2. 9. 2.]
 [0. 5. 2. 1.]
 [4. 6. 4. 3.]
 [9. 6. 3. 7.]
 [7. 4. 3. 5.]
 [7. 1. 8. 5.]
 [5. 4. 8. 2.]]


In [ ]:
A=np.arange(1,33).reshape(8,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
#splitting
print(np.vsplit(A,4))

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]]), array([[17, 18, 19, 20],
       [21, 22, 23, 24]]), array([[25, 26, 27, 28],
       [29, 30, 31, 32]])]


In [ ]:
print(np.vsplit(A,2))

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]]), array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])]


In [ ]:
np.vsplit(A,(3,6))#split it after 3rd row and 6th row

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30, 31, 32]]),
 array([], shape=(0, 8), dtype=int64)]

In [ ]:
A=np.arange(1,33).reshape(4,8)
print(A)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
print(np.hsplit(A,4))

[array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26]]), array([[ 3,  4],
       [11, 12],
       [19, 20],
       [27, 28]]), array([[ 5,  6],
       [13, 14],
       [21, 22],
       [29, 30]]), array([[ 7,  8],
       [15, 16],
       [23, 24],
       [31, 32]])]


In [ ]:
print(np.hsplit(A,(3,4)))

[array([[ 1,  2,  3],
       [ 9, 10, 11],
       [17, 18, 19],
       [25, 26, 27]]), array([[ 4],
       [12],
       [20],
       [28]]), array([[ 5,  6,  7,  8],
       [13, 14, 15, 16],
       [21, 22, 23, 24],
       [29, 30, 31, 32]])]


In [ ]:
print(np.hsplit(A,(2,5)))

[array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26]]), array([[ 3,  4,  5],
       [11, 12, 13],
       [19, 20, 21],
       [27, 28, 29]]), array([[ 6,  7,  8],
       [14, 15, 16],
       [22, 23, 24],
       [30, 31, 32]])]


In [ ]:
np.pi

3.141592653589793

In [ ]:
A = [np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
np.rad2deg(A)#convert radians to degrees

array([ 45.,  60.,  90., 180.])

In [ ]:
A = [60,45,90]
np.deg2rad(A)#convert degrees to radians

array([1.04719755, 0.78539816, 1.57079633])

In [ ]:
np.sin(1) #radians

0.8414709848078965

In [ ]:
np.cos(1)

0.5403023058681398

In [ ]:
np.tan(1)

1.5574077246549023

Statistics

In [ ]:
st=np.array([23,45,67,89,21,34])

In [ ]:
np.mean(st)

46.5

In [ ]:
np.median(st)

39.5

In [ ]:
np.std(st)

24.452334585202017

In [ ]:
np.var(st)

597.9166666666666

In [ ]:
C = np.arange(1,5).reshape(2,2)
print(C)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(C) #subpackage of numpy

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
C = np.arange(1,25).reshape(6,4)
print(C)
print(np.argmax(C))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
23


In [ ]:
C = np.floor(10*np.random.rand(24)).reshape(6,4)
print(C)
print(np.argmax(C))

[[1. 6. 4. 9.]
 [7. 1. 2. 8.]
 [9. 4. 4. 3.]
 [9. 1. 5. 9.]
 [4. 3. 1. 7.]
 [8. 0. 4. 9.]]
3


In [ ]:
C = 10*np.random.rand(24).reshape(6,4)
print(C)
print(np.argmax(C))

[[4.69306514 8.12214362 3.50047131 4.20354671]
 [0.38999588 9.61440725 4.33004428 4.4519259 ]
 [7.64355932 4.13822546 1.16709952 6.92739699]
 [0.65919129 6.78117078 1.9255183  6.64270658]
 [0.92131835 3.24744379 1.15462024 2.33186375]
 [7.61604365 5.67889394 4.57607551 3.98833361]]
5


In [ ]:
C= 10*np.random.rand(24).reshape(6,4)
print(C)
print(np.argmax(C,axis=1))

[[3.62705686 1.66394524 8.04761888 1.94618507]
 [2.43651038 8.25114551 6.44137075 6.03686669]
 [2.70511538 3.95499064 6.23763917 6.84303551]
 [8.64146396 5.81228747 1.47956572 8.3755428 ]
 [1.78760252 8.1429166  2.05112908 4.52844821]
 [4.57420744 3.19606541 5.5816307  8.30127752]]
[2 1 3 0 1 3]


In [ ]:
print(np.argmax(C,axis=0))

[3 1 0 3]


In [ ]:
print(np.argmin(C))

14


In [ ]:
print(np.argmin(C,axis=0))

[4 0 3 0]


In [ ]:
print(np.argmin(C,axis=1))

[1 0 0 2 0 1]


Searching

In [ ]:
#Find the indexs where the values are even
a=np.array([34,56,7,17,88,91])
print(np.where(a%2 == 0))

(array([0, 1, 4]),)


In [ ]:
#Find the indexs which are divisible by 6
a=np.array([24,16,7,17,54,60])
print(np.where(a%6 == 0))
print(a)

(array([0, 4, 5]),)
[24 16  7 17 54 60]


In [ ]:
#Used only for already sorted list
a = np.array([6,7,8,9,10])
x=np.searchsorted(a,8)
print(x)

2


In [ ]:
a = np.array([10,8,9,7])
x=np.searchsorted(a,8)#not applicalble for sorted list
print(x)

In [ ]:
#sorting array
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
arr=np.array([True,False,True]) #False=0,True=1
print(np.sort(arr))


[False  True  True]


In [ ]:
#2d sort - sorting happens within row
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
#array filter
arr=np.array([40,42,50,44,67,78])
x=[True,False,True,False,True,True] #filter list
newarr=arr[x]
print(newarr)

[40 50 67 78]


In [ ]:
arr=np.array([40,43,50,44,67,78]) #filter may be list or array
filt=np.where(arr%2 == 0)
print(filt)

(array([0, 2, 3, 5]),)


In [ ]:
arr[filt]

array([40, 50, 44, 78])

In [ ]:
names=np.array(["Lavanya","Dharani","Akhila"]) #zip function is used to combine two or more arrays and lists
initials=np.array(["P","K","T"])
for i,j in zip(initials,names):
  print(i,".",j)

P . Lavanya
K . Dharani
T . Akhila


In [ ]:
names=np.array(["Lavanya","Dharani","Akhila"])
initials=np.array(["P","K","T"])
num=np.array(["5B0","5B1","5C0"])
for i,j,k in zip(num,initials,names):
  print(i,".",j,".",k)

5B0 . P . Lavanya
5B1 . K . Dharani
5C0 . T . Akhila


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.multiply(a1,a2)
print(n)

[ 200  420  660  920 1200 1500]


In [ ]:
a1=np.array([10,21,30,40,50,60])
a2=np.array([20,21,2,20,25,25])
n=np.divide(a1,a2)
print(n)

[ 0.5  1.  15.   2.   2.   2.4]


In [ ]:
a1=np.array([10,21,30,40,50,60])
a2=np.array([20,21,2,20,25,25])
n=np.mod(a1,a2)
print(n)

[10  0  0  0  0 10]


In [ ]:
a1=np.array([10,21,30,40,50,60])
a2=np.array([3,2,2,7,10,7])
n=np.divmod(a1,a2)
print(n)

(array([ 3, 10, 15,  5,  5,  8]), array([1, 1, 0, 5, 0, 4]))


Logarithms

In [ ]:
a=1.2
print(np.log(a)) #natural log e

0.1823215567939546


In [ ]:
a=1.2
print(np.log2(a)) #log base 2

0.2630344058337938


In [ ]:
a=1.2
print(np.log10(a)) #log base 10

0.07918124604762482


In [ ]:
a=np.array([1,2,3,4,])
print(np.log(a)) #natural log e

[0.         0.69314718 1.09861229 1.38629436]


In [ ]:
a1=np.arange(1,10)
print(a1)
print(np.log2(a1)) #base2

[1 2 3 4 5 6 7 8 9]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [ ]:
a1=np.arange(1,10)
print(a1)
print(np.log10(a1)) #base10

[1 2 3 4 5 6 7 8 9]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


Other mathematical operations

In [ ]:
a2=np.array([5,6,7,10])
x=np.cumprod(a2)
print(x)

[   5   30  210 2100]


In [ ]:
a1=np.array([10,15,25,15]) #e2-e1
newarr=np.diff(a1)
print(newarr)

[  5  10 -10]


In [ ]:
num1=455
num2=665
x=np.lcm(num1,num2)
print(x)

8645


In [ ]:
num1=455
num2=665
x=np.gcd(num1,num2)
print(x)

35


In [ ]:
a2=np.array([5,6,7,10])
x=np.cumsum(a2)
print(x)

[ 5 11 18 28]


In [ ]:
a=np.array([12,15,60])
gc=np.gcd.reduce(a) #takes multiple inputs gives single output
print(gc)

3


In [ ]:
a=np.array([12,15,60])
lc=np.lcm.reduce(a) #takes multiple inputs gives single output
print(lc)

60
